/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'crawlingo-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./crawlingo-native.android-arm64.node')
          } else {
            nativeBinding = require('crawlingo-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'crawlingo-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./crawlingo-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('crawlingo-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'crawlingo-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./crawlingo-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('crawlingo-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'crawlingo-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./crawlingo-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('crawlingo-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'crawlingo-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./crawlingo-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('crawlingo-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'crawlingo-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./crawlingo-native.darwin-universal.node')
      } else {
        nativeBinding = require('crawlingo-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'crawlingo-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./crawlingo-native.darwin-x64.node')
          } else {
            nativeBinding = require('crawlingo-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'crawlingo-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./crawlingo-native.darwin-arm64.node')
          } else {
            nativeBinding = require('crawlingo-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'crawlingo-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./crawlingo-native.freebsd-x64.node')
      } else {
        nativeBinding = require('crawlingo-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'crawlingo-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crawlingo-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('crawlingo-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'crawlingo-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crawlingo-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('crawlingo-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'crawlingo-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crawlingo-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('crawlingo-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'crawlingo-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crawlingo-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('crawlingo-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'crawlingo-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crawlingo-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('crawlingo-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'crawlingo-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crawlingo-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('crawlingo-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'crawlingo-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crawlingo-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('crawlingo-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'crawlingo-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crawlingo-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('crawlingo-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'crawlingo-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./crawlingo-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('crawlingo-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { JsSession, JsPage, fetchPage, JsElementCollection, JsElement, JsDatasetResult, JsDataset, saveStructuredJson, saveStructuredCsv, JsCrawl, JsWatch } = nativeBinding

module.exports.JsSession = JsSession
module.exports.JsPage = JsPage
module.exports.fetchPage = fetchPage
module.exports.JsElementCollection = JsElementCollection
module.exports.JsElement = JsElement
module.exports.JsDatasetResult = JsDatasetResult
module.exports.JsDataset = JsDataset
module.exports.saveStructuredJson = saveStructuredJson
module.exports.saveStructuredCsv = saveStructuredCsv
module.exports.JsCrawl = JsCrawl
module.exports.JsWatch = JsWatch
