from typing import Callable, Any

class Page:
    url: str
    status: int
    def __init__(
        self,
        url: str,
        auto_match: bool = False,
        timeout: int = 30,
        retries: int = 3,
        headers: dict[str, str] | None = None,
        cookies: dict[str, str] | None = None,
        proxy: str | None = None,
    ) -> None: ...
    def html(self) -> str: ...
    def title(self) -> str: ...
    def css(self, selector: str) -> ElementCollection: ...
    def xpath(self, query: str) -> ElementCollection: ...
    def find_text(self, text: str) -> ElementCollection: ...
    def after_text(self, text: str) -> ElementCollection: ...
    def before_text(self, text: str) -> ElementCollection: ...
    def regex(self, pattern: str) -> ElementCollection: ...

class Element:
    def text(self) -> str: ...
    def html(self) -> str: ...
    def attr(self, name: str) -> str | None: ...
    def attrs(self) -> dict[str, str]: ...
    def parent(self) -> Element | None: ...
    def children(self) -> ElementCollection: ...
    def next(self) -> Element | None: ...
    def prev(self) -> Element | None: ...
    def siblings(self) -> ElementCollection: ...

class ElementCollection:
    def first(self) -> Element | None: ...
    def last(self) -> Element | None: ...
    def nth(self, n: int) -> Element | None: ...
    def text(self) -> str: ...
    def texts(self) -> list[str]: ...
    def attr(self, name: str) -> str | None: ...
    def attrs(self) -> dict[str, str]: ...
    def __len__(self) -> int: ...

class Dataset:
    def __init__(self, url: str, session: Session) -> None: ...
    def field(
        self,
        name: str,
        selector: str,
        selector_type: str = "css",
        transform: Callable[[str], str] | None = None,
        default: str | None = None,
    ) -> Dataset: ...
    def build(self) -> DatasetResult: ...
    def build_async(self) -> DatasetResult: ...

class DatasetResult:
    def to_json(self, path: str) -> None: ...
    def to_csv(self, path: str) -> None: ...
    def to_parquet(self, path: str) -> None: ...
    def to_dict(self) -> dict[str, str]: ...
    def __getitem__(self, key: str) -> str: ...

class Crawl:
    def __init__(self, start_url: str, session: Session) -> None: ...
    def follow(self, selector: str) -> Crawl: ...
    def limit(self, pages: int) -> Crawl: ...
    def depth(self, max_depth: int) -> Crawl: ...
    def field(
        self,
        name: str,
        selector: str,
        selector_type: str = "css",
        default: str | None = None,
    ) -> Crawl: ...
    def concurrency(self, n: int) -> Crawl: ...
    def delay(self, seconds: float) -> Crawl: ...
    def webhook(self, url: str) -> Crawl: ...
    def schedule(self, interval_seconds: int) -> None: ...
    def build(self) -> list[DatasetResult]: ...

class ChangeEvent:
    field: str
    old_value: str | None
    new_value: str | None
    event_type: str

class Watch:
    def __init__(self, url: str, session: Session) -> None: ...
    def field(self, name: str, selector: str) -> Watch: ...
    def interval(self, seconds: int) -> Watch: ...
    def on_change(self, fn: Callable[[ChangeEvent], None]) -> Watch: ...
    def on_price_change(self, fn: Callable[[ChangeEvent], None]) -> Watch: ...
    def on_stock_change(self, fn: Callable[[ChangeEvent], None]) -> Watch: ...
    def on_element_added(self, fn: Callable[[ChangeEvent], None]) -> Watch: ...
    def on_element_removed(self, fn: Callable[[ChangeEvent], None]) -> Watch: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...

class Session:
    def __init__(self) -> None: ...
    def auto_match(self, enabled: bool) -> None: ...
    def timeout(self, seconds: int) -> None: ...
    def headers(self, headers: dict[str, str]) -> None: ...
    def cookies(self, cookies: dict[str, str]) -> None: ...
    def proxy(self, proxy: str | None) -> None: ...
    def rate_limit(self, requests_per_second: float) -> None: ...
    def fingerprint_path(self, path: str) -> None: ...
    def fetcher_tier(self, tier: str) -> None: ...
    def browser_profile(self, profile: str | None) -> None: ...
    def auto_match_weights(self, weights: dict[str, float]) -> None: ...
    def proxy_pool(self, proxies: list[str]) -> None: ...
    def proxy_provider(self, url: str | None) -> None: ...
